### ISSUE TITLE
회원가입 성공 시 메일 발송 서비스

### ISSUE THREAD

**Issue by heroleggo** [boostcampwm-2022/web07-zokboo.com#72]
## 설명

회원가입 성공 시 이메일이 인증되지 않은 상태이기 때문에, 메일을 발송하여 메일에 있는 링크 접속 시 인증이 완료되도록 구조 개선 진행 예정

## Tasks

- [ ] 테스트 용 이메일 계정 생성 및 SMTP 설정 진행
- [ ] 이메일 서비스 구현 (Nodemailer 활용)
- [ ] 유저 쪽 인증 여부 필드 추가 및 회원가입 시 미인증 상태로 두도록 코드 수정
- [ ] 받은 메일의 링크 클릭 시 인증이 진행되고, 인증 상태로 변경하는 API 구현
